events{

}

http{
 upstream backend{
    server sever1:5000;
    server sever2:5000;          # backend is a variable assigned in server 
    server sever3:5000;
 }
    server{
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}